=== OhmSweetOhm/CobieQCReporter/src/main/resources/etc/xsl_xml/Picklist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="picklist.cobie.prairiesky.org" xmlns:ps="picklist.cobie.prairiesky.org" targetNamespace="picklist.cobie.prairiesky.org" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:element name="PicklistValue" type="xs:string"/>
	<xs:element name="Picklist" type="PicklistType"/>
	<xs:element name="SheetPicklists" type="SheetPicklistCollectionType"/>
	<xs:element name="CobiePicklists" type="CobiePicklistsType"/>
	<xs:complexType name="CobiePicklistsType">
		<xs:sequence>
			<xs:element ref="SheetPicklists" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SheetPicklistCollectionType">
		<xs:sequence>
			<xs:element ref="Picklist" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="SheetName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PicklistType">
		<xs:sequence>
			<xs:element ref="PicklistValue" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ColumnName" type="xs:string" use="required" form="unqualified"/>
	</xs:complexType>
</xs:schema>

=== OhmSweetOhm/CobieQCReporter/src/main/resources/etc/xsl_xml/samplePicklist.xml
<?xml version="1.0" encoding="UTF-8"?>
<CobiePicklists xmlns="picklist.cobie.prairiesky.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="picklist.cobie.prairiesky.org file:///C:/Users/Bogen/Documents/Java/BIMserver-1.4.0-FINAL-2015-11-04/COBieCommandLineTools/xsl_xml/Picklist.xsd">
	<SheetPicklists SheetName="Type">
		<Picklist ColumnName="Category">
			<PicklistValue>Pumps</PicklistValue>
			<PicklistValue>Valves</PicklistValue>
			<PicklistValue>Motors</PicklistValue>
		</Picklist>
		<Picklist ColumnName="Shape">
			<PicklistValue>Circle</PicklistValue>
			<PicklistValue>Triangle</PicklistValue>
			<PicklistValue>Square</PicklistValue>
		</Picklist>
	</SheetPicklists>
	<SheetPicklists SheetName="Space">
		<Picklist ColumnName="Category">
			<PicklistValue>Bathrooms</PicklistValue>
			<PicklistValue>Mechanical Rooms</PicklistValue>
		</Picklist>
	</SheetPicklists>
</CobiePicklists>
